### ISSUE TITLE
Alfred App Integration ? 

### ISSUE THREAD

**Issue by SethCalkins** [nicholasrobinson/XfinityControlWeb#1]
Any Possibility of seeing [Alfred App](https://www.alfredapp.com) Integration ?

**Comment by nicholasrobinson** [comment]
Interesting idea. Let me see what I can knock together this weekend!

**Comment by nicholasrobinson** [comment]
I threw together a very simple Alfred workflow. The necessary changes are landed at [1fde262](https://github.com/nicholasrobinson/XfinityControlWeb/commit/1fde262056837dab9e6eabdbdcf3edb01b5dc33d).

I tried to make the setup relatively straightforward, but there is definitely room for improvement...

In short:
1. Clone the latest version of the repository.
2. sudo pip install -r requirements.txt
3. Import the workflow by double-clicking "alfred_workflow.alfredworkflow", then clicking "Import".
4. Configure the workflow and variable by clicking the "[x]" icon in the upper-right:
5. Change the workflow environment variable "Value" to the location of your repository. e.g. `/Users/<YOUR_USERNAME>/XfinityControlWeb`
6. Add a keychain item with the following values:
- Keychain Item Name: XfinityControlWeb
- Account Name: credentials
- Password: `<XFINITY_USERNAME>:<XFINITY_PASSWORD>`

Pull requests welcome if you have any way to make the workflow setup more user friendly.

Let me know if it works for you! If so please close the issue.
