### ISSUE TITLE
There seems to be a missing key in a returned status object rovi

### ISSUE THREAD

**Issue by zukeru** [nicholasrobinson/XfinityControlWeb#2]
I'm getting a key error when it looks for something called headband, from what I can guess its a guid returned but I look at the object and there is no guid

from xfinity_control.py its this parameter
`self._headend = self._profile["UnifiedVal"]["uisTvPrefs"]["rovi"]["headend"]`

the values of 

`dict: {u'requestUri': u'https://uis-prod.codebig2.net/users/{removedforsecurity}Comcast.USRIMS/preferences/tv', u'cache': u'CACHE_MISS', u'result': u'GUID Not Found In UIS'}
`
Here is the error that is being output:

Not sure whats going on, am I missing something with my comcast service my device has remote enabled true. Not really sure what "headband" is...

```
pydev debugger: starting (pid: 70092)
Enter xfinity credentials.
Traceback (most recent call last):
  File "C:\eclipse\plugins\org.python.pydev_5.0.0.201605051159\pysrc\pydevd.py", line 1530, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\eclipse\plugins\org.python.pydev_5.0.0.201605051159\pysrc\pydevd.py", line 937, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\Administraor\workspace\Scripts\alexa-automation\XfinityControlWeb\__main__.py", line 16, in <module>
    xfinity_control = XfinityControl(username, password)
  File "C:\Users\Administraor\workspace\Scripts\alexa-automation\XfinityControlWeb\xfinity_control_web\xfinity_control.py", line 32, in __init__
    self._headend = self._profile["UnifiedVal"]["uisTvPrefs"]["rovi"]["headend"]
KeyError: 'rovi'
```

**Comment by zukeru** [comment]
I can see both the devices in my house, and I can tell which one can and which one cant be controlled in variable explore but I'm not sure whats missing.

**Comment by nicholasrobinson** [comment]
The traceback seems to indicate that your profile payload (returned by http://xfinitytv.comcast.net/xtv/authkey/user) is missing the "rovi" key. The "headend" parameter is only used for fetching the channel listings, so the API should work fine for you with my changes landed at [e0769ea](https://github.com/nicholasrobinson/XfinityControlWeb/commit/e0769ea56484a2753aeaf6432ec601025bad6438), however the XfinityControl::get_lineup() function will not return anything - which means you will only be able to change channel by number and not by name...

I can only assume that your local Comcast uses a different API for providing channel lineup/listing information. I would recommend logging into your Comcast account and finding the channel listing page - this should be on the same page that allows you to change channels. If you look at the "network" tab in the developer tools in Google Chrome you should be able to see the relevant API calls.

If you find any more information about your local channels API, please let me know and I will attempt to incorporate it into the codebase. Regardless, the latest commit should allow you to use the API successfully.

Let me know how it goes! Please close if this resolves your issue.

**Comment by zukeru** [comment]
I used version 0.1.9 maybe its a windows thing. Should I try to use mac or linux ? I can probably toss a vm up and try it. I manually changed all the files to not have the deployment on them and still the same error.

**Comment by nicholasrobinson** [comment]
Can you delete the entire directory and re-clone? If you hit an error please post the trace back.

**Comment by nicholasrobinson** [comment]
Was this issue resolved?
